---
- name: Prep Admin Node
  remote_user: root

  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
    
    - name: Install packages
      apt:
        name: curl,vim
        autoremove: true
    
    # https://kubernetes.io/docs/tasks/tools/
    - name: Download kubectl binary
      ansible.builtin.shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    
    - name: Install kubectl
      ansible.builtin.shell: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    
    - name: Validate kubectl install
      ansible.builtin.shell: kubectl version --client
    
    - name: Allow all access to tcp port 6443
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp
    
    - name: Download containerd archive
      ansible.builtin.shell: curl -O https://github.com/containerd/containerd/archive/refs/tags/api/v1.7.19.tar.gz
    
    - name: Extract the archive to the expected directory
      ansible.builtin.shell: tar Cxzvf /usr/local containerd-1.6.2-linux-amd64.tar.gz
      
    - name: Start the containerd service with systemd
      ansible.builtin.systemd_service:
        name: containerd
        daemon_reload: true
        state: started
        enabled: true
    
    # I left off here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports

