---
- name: Update Cluster Nodes
  hosts: cluster
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  become: true

  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
    
    - name: Install utilities
      apt:
        name: vim,curl
        autoremove: true
